### ISSUE TITLE
无法启动Activity

### ISSUE THREAD

**Issue by JDChi** [McoyJiang/LagouAndroidShare#5]
>     java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.asmlifecycledemo/com.example.asmlifecycledemo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.asmlifecycledemo.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.asmlifecycledemo-HlJlwafushUImzYDu1LOQg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.asmlifecycledemo-HlJlwafushUImzYDu1LOQg==/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3100)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1804)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6907)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.asmlifecycledemo.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.asmlifecycledemo-HlJlwafushUImzYDu1LOQg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.asmlifecycledemo-HlJlwafushUImzYDu1LOQg==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3100) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1804) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6907) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by JDChi** [comment]
plugin会生成多个iml文件，把这些文件都删掉后就可以正常打开app了。但仍打印不出日志。
